name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.released.outputs.tag-name }}
    steps:
      - uses: actions/checkout@v4

      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: get released tag
        id: released
        run: |
          echo "tag-name=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

  update-major-tag:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.tag-name }}

      - name: setup git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

      - name: update major tag
        run: |
          export TAG_NAME="${{ needs.release.outputs.tag-name }}"
          export TAG_MAJOR="${TAG_NAME%%.*}"
          git tag --force -a "${TAG_MAJOR}" -m "Release ${TAG_NAME}"
          git push --force origin "${TAG_MAJOR}"

  update-latest-tag:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.tag-name }}

      - name: setup git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

      - name: update latest tag
        run: |
          git tag --force -a "latest" -m "Release Latest"
          git push --force origin "latest"